name: Release
on:
  push:
    branches:
      - main

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  release:
    name: Release
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/gh-actions/setup

      - name: Check packages for common errors
        run: pnpm turbo --filter "./packages/*" build lint test typecheck

      # Using custom token `MY_GITHUB_TOKEN` with more access to avoid rate limiting
      - name: Create Release
        id: changeset
        uses: changesets/action@v1.4.7
        with:
          commit: "chore(release): 📦 version packages"
          title: "chore(release): 📦  version packages"
          publish: npx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

        # Changeset has some issues with pnpm so we sync it up manually
      - name: Sync lockfile if necessary
        if: steps.changeset.outputs.hasChangesets == 'true'
        run: |
          git checkout changeset-release/main
          pnpm install --no-frozen-lockfile
          git add .
          git commit -m "chore(release): 📦 sync lockfile"
          git push origin changeset-release/main